# Copyright (c) 2026, Abhishek Kumar and contributors
# For license information, please see license.txt
"""Revert CRM Project Estimation rows that were force-set to ``status='Done'``
by the cascade feature introduced in commit 5a8ce6e (May 2 2026) and the
companion backfill patch ``backfill_estimation_done_for_terminal_projects``
that ran on prod at 2026-05-04 10:26:40 IST.

The mapping below was computed offline from two PostgreSQL snapshots
(2026-05-04 pre-deploy + 2026-05-07 current) using a 3-layer detection:

  Layer 1 (6 rows): rows with ``auto_derived: true`` Version trail showing
                    ``status: <prior> -> Done`` from the live cascade.
  Layer 2 (618 rows): rows present in the pre-deploy snapshot at non-Done
                      whose current ``modified`` timestamp is <= deploy time
                      (proves no user touched them post-backfill).

Rows currently at Done that fell into none of the above buckets — pre-existing
manual Dones (29), post-deploy creations (8), or backfill-flipped-then-user-
touched (0) — are intentionally NOT in this plan and stay at Done.

The runtime drift guard ``current_status == 'Done'`` ensures this patch is
idempotent and safe even if the live DB has drifted further since the plan
was computed: any row whose status has been manually changed away from Done
in the meantime is skipped.

Uses ``update_modified=False`` to preserve audit fidelity — this is retroactive
data alignment, not a user edit.
"""
import csv
import frappe


REVERT_PLAN = {
    '14th Floor Embassy one Embark - Legacy BCS': 'Pending',
    '14th Floor Embassy one Embark - Legacy BOQ': 'BOQ Submitted',
    '320  SKAN  SP9 - HVAC  TBOQ  RFQ - Legacy BCS': 'Pending',
    '320  SKAN  SP9 - HVAC  TBOQ  RFQ - Legacy BOQ': 'BOQ Submitted',
    '3F Proto Lab - Legacy BCS': 'Pending',
    '3F Proto Lab - Legacy BOQ': 'BOQ Submitted',
    '5th Floor Ecospace Tech Park - Legacy BCS': 'Pending',
    '5th Floor Ecospace Tech Park - Legacy BOQ': 'BOQ Submitted',
    '80TD-HYD - Legacy BCS': 'Pending',
    '80TD-HYD - Legacy BOQ': 'BOQ Submitted',
    '83 MU - Legacy BCS': 'Pending',
    '83 MU - Legacy BOQ': 'BOQ Submitted',
    '86 Saab - Legacy BCS': 'Pending',
    '86 Saab - Legacy BOQ': 'BOQ Submitted',
    '87 PRE - Legacy BCS': 'Pending',
    '87 PRE - Legacy BOQ': 'BOQ Submitted',
    '88 Upcoming Project - Legacy BCS': 'Pending',
    '88 Upcoming Project - Legacy BOQ': 'BOQ Submitted',
    'AB MAURI INDORE - Legacy BCS': 'Pending',
    'AB MAURI INDORE - Legacy BOQ': 'BOQ Submitted',
    'AC BOQ Maruthi Chember - HVAC BCS': 'Pending',
    'AC BOQ Maruthi Chember - HVAC BOQ': 'BOQ Submitted',
    'AISATS - Legacy BCS': 'Pending',
    'AISATS - Legacy BOQ': 'BOQ Submitted',
    'AISATS Banglore CLC - Legacy BCS': 'Pending',
    'AISATS Banglore CLC - Legacy BOQ': 'BOQ Submitted',
    'ALORICA MYSORE ROAD - HVAC Ducting BOQ': 'BOQ Submitted',
    'AMAZON - ELV BCS': 'Pending',
    'AMAZON - ELV BOQ': 'BOQ Submitted',
    'AMAZON - Electrical BCS': 'Pending',
    'AMAZON - Electrical BOQ': 'BOQ Submitted',
    'AMAZON - HVAC BCS': 'Pending',
    'AMAZON - HVAC BOQ': 'BOQ Submitted',
    'AMAZON - Legacy BCS': 'Pending',
    'AMAZON - Legacy BOQ': 'BOQ Submitted',
    'ANSR - Gurgaon - Legacy BCS': 'Pending',
    'ANSR - Gurgaon - Legacy BOQ': 'BOQ Submitted',
    'ANSR 5th Floor - Legacy BCS': 'Pending',
    'ANSR 5th Floor - Legacy BOQ': 'BOQ Submitted',
    'AOCC - Legacy BCS': 'Pending',
    'AOCC - Legacy BOQ': 'BOQ Submitted',
    'AOCC_SC_HVAC Works - HVAC BCS': 'Pending',
    'AOCC_SC_HVAC Works - HVAC BOQ': 'BOQ Submitted',
    'AON - Legacy BCS': 'Pending',
    'AON - Legacy BOQ': 'BOQ Submitted',
    'AWF Chennai - Legacy BCS': 'Pending',
    'AWF Chennai - Legacy BOQ': 'BOQ Submitted',
    'Abhee Shine - HVAC BCS': 'Pending',
    'Abhee Shine - HVAC BOQ': 'BOQ Submitted',
    'Accenture - HVAC BCS': 'Pending',
    'Accenture - HVAC BOQ': 'BOQ Submitted',
    'Accenture Project - Acme Interiors - Legacy BCS': 'Pending',
    'Accenture Project - Acme Interiors - Legacy BOQ': 'BOQ Submitted',
    'Accenture Project - Krayons Interiors - Legacy BCS': 'Pending',
    'Accenture Project - Krayons Interiors - Legacy BOQ': 'BOQ Submitted',
    'Accenture Project - Legacy BCS': 'Pending',
    'Accenture Project - Legacy BOQ': 'BOQ Submitted',
    'Adecco ODC - Legacy BCS': 'Pending',
    'Adecco ODC - Legacy BOQ': 'BOQ Submitted',
    'Aditya Brila Ikgloo - Legacy BCS': 'Pending',
    'Aditya Brila Ikgloo - Legacy BOQ': 'BOQ Submitted',
    'Adrainse Tender - ELV BCS': 'Pending',
    'Adrainse Tender - ELV BOQ': 'BOQ Submitted',
    'Adrainse Tender - Electrical BCS': 'Pending',
    'Adrainse Tender - Electrical BOQ': 'BOQ Submitted',
    'Adrainse Tender - HVAC BCS': 'Pending',
    'Adrainse Tender - HVAC BOQ': 'BOQ Submitted',
    'Adrainse Tender - Legacy BCS': 'Pending',
    'Adrainse Tender - Legacy BOQ': 'BOQ Submitted',
    'Advance T2- Marketing Office - Legacy BCS': 'Pending',
    'Advance T2- Marketing Office - Legacy BOQ': 'BOQ Submitted',
    'Airtel Kochi - Legacy BCS': 'Pending',
    'Airtel Kochi - Legacy BOQ': 'BOQ Submitted',
    'Airtel Project - Legacy BCS': 'Pending',
    'Airtel Project - Legacy BOQ': 'BOQ Submitted',
    'Alorica @BLR - Legacy BCS': 'Pending',
    'Alorica @BLR - Legacy BOQ': 'BOQ Submitted',
    'Alumini Block - Legacy BCS': 'Pending',
    'Alumini Block - Legacy BOQ': 'BOQ Submitted',
    'Amazon BLR - Legacy BCS': 'Pending',
    'Amazon BLR - Legacy BOQ': 'BOQ Submitted',
    'Ankuraa Group - Legacy BCS': 'Pending',
    'Ankuraa Group - Legacy BOQ': 'BOQ Submitted',
    'Aster DM Healthcare - Legacy BCS': 'Pending',
    'Aster DM Healthcare - Legacy BOQ': 'BOQ Submitted',
    'Aster New Corporate Office - Legacy BCS': 'Pending',
    'Aster New Corporate Office - Legacy BOQ': 'BOQ Submitted',
    'BBI Domestic Lounge - Legacy BCS': 'Pending',
    'BBI Domestic Lounge - Legacy BOQ': 'BOQ Submitted',
    'BCIT 8th Floor - Legacy BCS': 'Pending',
    'BCIT 8th Floor - Legacy BOQ': 'BOQ Submitted',
    'BECHTEL - Legacy BCS': 'Pending',
    'BECHTEL - Legacy BOQ': 'BOQ Submitted',
    'BEWAKOOF - Legacy BCS': 'Pending',
    'BEWAKOOF - Legacy BOQ': 'BOQ Submitted',
    'BLR Project - HVAC BCS': 'Pending',
    'BLR Project - HVAC BOQ': 'BOQ Submitted',
    'BP MEP Centerlised - Legacy BCS': 'Pending',
    'BP MEP Centerlised - Legacy BOQ': 'BOQ Submitted',
    'BTR 9F - Legacy BCS': 'Pending',
    'BTR 9F - Legacy BOQ': 'BOQ Submitted',
    'Bangalore International Airport Limited BIAL - Electrical BOQ': 'New',
    'Bangalore International Airport Limited BIAL - Extinguishers BOQ': 'New',
    'Bangalore International Airport Limited BIAL - FA BOQ': 'New',
    'Bangalore International Airport Limited BIAL - Fire Sprinkler System BOQ': 'New',
    'Bangalore International Airport Limited BIAL - HVAC BOQ': 'New',
    'Bangalore International Airport Limited BIAL - Signages BOQ': 'New',
    'Bhartiya Urban Pvt.LTD - Legacy BCS': 'Pending',
    'Bhartiya Urban Pvt.LTD - Legacy BOQ': 'BOQ Submitted',
    'Bidadi project ( Client Toyota ) - Legacy BCS': 'Pending',
    'Bidadi project ( Client Toyota ) - Legacy BOQ': 'BOQ Submitted',
    'Boardroom Project - Legacy BCS': 'Pending',
    'Boardroom Project - Legacy BOQ': 'BOQ Submitted',
    'Bold and Beyond - Electrical BCS': 'Pending',
    'Bold and Beyond - Electrical BOQ': 'BOQ Submitted',
    'Buhler HVAC - Legacy BCS': 'Pending',
    'Buhler HVAC - Legacy BOQ': 'BOQ Submitted',
    'Buzzwork - Legacy BCS': 'Pending',
    'Buzzwork - Legacy BOQ': 'BOQ Submitted',
    'CHN - Legacy BCS': 'Pending',
    'CHN - Legacy BOQ': 'BOQ Submitted',
    'CLAY WORKS ELE  AND ELV - Legacy BCS': 'Pending',
    'CLAY WORKS ELE  AND ELV - Legacy BOQ': 'BOQ Submitted',
    'CLAY WORKS SENETE - HVAC BCS': 'Pending',
    'CLAY WORKS SENETE - HVAC BOQ': 'BOQ Submitted',
    'CNH Creche - Lucknow - Legacy BCS': 'Pending',
    'CNH Creche - Lucknow - Legacy BOQ': 'BOQ Submitted',
    'CNH Creche - Pithampur - Legacy BCS': 'Pending',
    'CNH Creche - Pithampur - Legacy BOQ': 'BOQ Submitted',
    'COGNITE - Legacy BCS': 'Pending',
    'COGNITE - Legacy BOQ': 'BOQ Submitted',
    'CTS - Building 20- Raheja @ Hyderabad - Legacy BCS': 'Pending',
    'CTS - Building 20- Raheja @ Hyderabad - Legacy BOQ': 'BOQ Submitted',
    'CTS - Legacy BCS': 'Pending',
    'CTS - Legacy BOQ': 'BOQ Submitted',
    'CTS - Manyata Tech Park - Legacy BCS': 'Pending',
    'CTS - Manyata Tech Park - Legacy BOQ': 'BOQ Submitted',
    'CTS Engineering Studio Bangalore  Artizen - Legacy BCS': 'Pending',
    'CTS Engineering Studio Bangalore  Artizen - Legacy BOQ': 'BOQ Submitted',
    'CTS Engineering Studio Bangalore - Om Sai - Legacy BCS': 'Pending',
    'CTS Engineering Studio Bangalore - Om Sai - Legacy BOQ': 'BOQ Submitted',
    'CTS-Charter Lab - Electrical BCS': 'Pending',
    'CTS-Charter Lab - Electrical BOQ': 'BOQ Submitted',
    'CUPID - Legacy BCS': 'Pending',
    'CUPID - Legacy BOQ': 'BOQ Submitted',
    'Capex - Legacy BCS': 'Pending',
    'Capex - Legacy BOQ': 'BOQ Submitted',
    'Cargill Proposed Renovation - Electrical BOQ': 'Revision Submitted',
    'Cargill Proposed Renovation - HVAC BOQ': 'Revision Submitted',
    'Cargill Proposed Renovation - UPS BOQ': 'Revision Submitted',
    'Century Eden - Legacy BCS': 'Pending',
    'Century Eden - Legacy BOQ': 'BOQ Submitted',
    'Chennai HVAC and BMS - Legacy BCS': 'Pending',
    'Chennai HVAC and BMS - Legacy BOQ': 'BOQ Submitted',
    'Chennai Project - Legacy BCS': 'Pending',
    'Chennai Project - Legacy BOQ': 'BOQ Submitted',
    'Chiller Project - Legacy BCS': 'Pending',
    'Chiller Project - Legacy BOQ': 'BOQ Submitted',
    'Cinepolis Regal - Electrical BCS': 'Pending',
    'Cinepolis Regal - Electrical BOQ': 'BOQ Submitted',
    'Cinepolis S3 Chennai - Legacy BCS': 'Pending',
    'Cinepolis S3 Chennai - Legacy BOQ': 'BOQ Submitted',
    'Citrine-Hebbal - Legacy BCS': 'Pending',
    'Citrine-Hebbal - Legacy BOQ': 'BOQ Submitted',
    'Clayworks Rhapsody(TE) - Whitefield - Legacy BCS': 'Pending',
    'Clayworks Rhapsody(TE) - Whitefield - Legacy BOQ': 'BOQ Submitted',
    'Clayworks Senate 5F Bangalore - Legacy BCS': 'Pending',
    'Clayworks Senate 5F Bangalore - Legacy BOQ': 'BOQ Submitted',
    'Club House HVAC - Legacy BCS': 'Pending',
    'Club House HVAC - Legacy BOQ': 'BOQ Submitted',
    'Cochin Port Trust - Legacy BCS': 'Pending',
    'Cochin Port Trust - Legacy BOQ': 'BOQ Submitted',
    'Cognizant - Legacy BCS': 'Pending',
    'Cognizant - Legacy BOQ': 'BOQ Submitted',
    'Cognizant Technology Solution - Legacy BCS': 'Pending',
    'Cognizant Technology Solution - Legacy BOQ': 'BOQ Submitted',
    'Commerz3FGKN Areospace - Legacy BCS': 'Pending',
    'Commerz3FGKN Areospace - Legacy BOQ': 'BOQ Submitted',
    'D n B - Legacy BCS': 'Pending',
    'D n B - Legacy BOQ': 'BOQ Submitted',
    'DLF Chennai - Legacy BCS': 'Pending',
    'DLF Chennai - Legacy BOQ': 'BOQ Submitted',
    'DS GROUP BNG - Legacy BCS': 'Pending',
    'DS GROUP BNG - Legacy BOQ': 'BOQ Submitted',
    'Daimler Chennai - Legacy BCS': 'Pending',
    'Daimler Chennai - Legacy BOQ': 'BOQ Submitted',
    'Davenegre Pub - Electrical BCS': 'Pending',
    'Davenegre Pub - Electrical BOQ': 'BOQ Submitted',
    'Deutsche bank - Legacy BCS': 'Pending',
    'Deutsche bank - Legacy BOQ': 'BOQ Submitted',
    'Dexian - Legacy BCS': 'Pending',
    'Dexian - Legacy BOQ': 'BOQ Submitted',
    'Drools - Legacy BCS': 'Pending',
    'Drools - Legacy BOQ': 'BOQ Submitted',
    'Drools Blr - Legacy BCS': 'Pending',
    'Drools Blr - Legacy BOQ': 'BOQ Submitted',
    'ECO WORLD_Oculus - Electrical BCS': 'Pending',
    'ECO WORLD_Oculus - Electrical BOQ': 'BOQ Submitted',
    'ECO WORLD_Oculus - HVAC BCS': 'Pending',
    'ECO WORLD_Oculus - HVAC BOQ': 'BOQ Submitted',
    'ECO WORLD_Oculus - Legacy BCS': 'Pending',
    'ECO WORLD_Oculus - Legacy BOQ': 'BOQ Submitted',
    'ELV work at Residency road Bangalore - Legacy BCS': 'Pending',
    'ELV work at Residency road Bangalore - Legacy BOQ': 'BOQ Submitted',
    'EXL @ Banglore - Legacy BCS': 'Pending',
    'EXL @ Banglore - Legacy BOQ': 'BOQ Submitted',
    'EXL AT KOCHI - HVAC BCS': 'Pending',
    'EXL AT KOCHI - HVAC BOQ': 'BOQ Submitted',
    'EY - BANGALORE CHENNAI TVM - Legacy BCS': 'Pending',
    'EY - BANGALORE CHENNAI TVM - Legacy BOQ': 'BOQ Submitted',
    'EY RMZ 1st Floor - Legacy BCS': 'Pending',
    'EY RMZ 1st Floor - Legacy BOQ': 'BOQ Submitted',
    'Ethereal Hotel - Legacy BCS': 'Pending',
    'Ethereal Hotel - Legacy BOQ': 'BOQ Submitted',
    'FATHIMUTTU HOSPITAL - Legacy BCS': 'Pending',
    'FATHIMUTTU HOSPITAL - Legacy BOQ': 'BOQ Submitted',
    'FES Works - Legacy BCS': 'Pending',
    'FES Works - Legacy BOQ': 'BOQ Submitted',
    'Fanuc Project - Electrical BCS': 'Pending',
    'Fanuc Project - Electrical BOQ': 'BOQ Submitted',
    'Featherlite MEP - Legacy BCS': 'Pending',
    'Featherlite MEP - Legacy BOQ': 'BOQ Submitted',
    'Flipkart - FAPA BCS': 'Pending',
    'Flipkart - FAPA BOQ': 'BOQ Submitted',
    'Flipkart - HVAC BCS': 'Pending',
    'Flipkart - HVAC BOQ': 'BOQ Submitted',
    'Flipkart - Legacy BCS': 'Pending',
    'Flipkart - Legacy BOQ': 'BOQ Submitted',
    'Fujitsu - Legacy BCS': 'Pending',
    'Fujitsu - Legacy BOQ': 'BOQ Submitted',
    'Fujitsu noida - Legacy BCS': 'Pending',
    'Fujitsu noida - Legacy BOQ': 'BOQ Submitted',
    'GC Mep Boq - Legacy BCS': 'Pending',
    'GC Mep Boq - Legacy BOQ': 'BOQ Submitted',
    'GC Project - ELV BCS': 'Pending',
    'GC Project - ELV BOQ': 'BOQ Submitted',
    'GC Project - Electrical BCS': 'Pending',
    'GC Project - Electrical BOQ': 'BOQ Submitted',
    'GC Project - HVAC BCS': 'Pending',
    'GC Project - HVAC BOQ': 'BOQ Submitted',
    'GC Project - Legacy BCS': 'Pending',
    'GC Project - Legacy BOQ': 'BOQ Submitted',
    'GM-BLR-RFQ - Legacy BCS': 'Pending',
    'GM-BLR-RFQ - Legacy BOQ': 'BOQ Submitted',
    'GREAVES - Legacy BCS': 'Pending',
    'GREAVES - Legacy BOQ': 'BOQ Submitted',
    'Godrej Sanctuary - Indira Nagar - ELV BCS': 'Pending',
    'Godrej Sanctuary - Indira Nagar - ELV BOQ': 'BOQ Submitted',
    'Godrej Sanctuary - Indira Nagar - Electrical BCS': 'Pending',
    'Godrej Sanctuary - Indira Nagar - Electrical BOQ': 'BOQ Submitted',
    'Godrej Sanctuary - Indira Nagar - HVAC BCS': 'Pending',
    'Godrej Sanctuary - Indira Nagar - HVAC BOQ': 'BOQ Submitted',
    'Godrej Sanctuary - Indira Nagar - Legacy BCS': 'Pending',
    'Godrej Sanctuary - Indira Nagar - Legacy BOQ': 'BOQ Submitted',
    'Guwahati International Airport Limited - Legacy BCS': 'Pending',
    'Guwahati International Airport Limited - Legacy BOQ': 'BOQ Submitted',
    'H and M Production Office - ELV BCS': 'Pending',
    'H and M Production Office - ELV BOQ': 'BOQ Submitted',
    'H and M Production Office - Electrical BCS': 'Pending',
    'H and M Production Office - Electrical BOQ': 'BOQ Submitted',
    'H and M Production Office - HVAC BCS': 'Pending',
    'H and M Production Office - HVAC BOQ': 'BOQ Submitted',
    'H and M Production Office - Legacy BCS': 'Pending',
    'H and M Production Office - Legacy BOQ': 'BOQ Submitted',
    'H n M - Electrical BCS': 'Pending',
    'H n M - Electrical BOQ': 'BOQ Submitted',
    'HCL MM116_MM117 - Legacy BCS': 'Pending',
    'HCL MM116_MM117 - Legacy BOQ': 'BOQ Submitted',
    'HCL Restroom Refurbishment - Legacy BCS': 'Pending',
    'HCL Restroom Refurbishment - Legacy BOQ': 'BOQ Submitted',
    'HCL SEZ Campus - Legacy BCS': 'Pending',
    'HCL SEZ Campus - Legacy BOQ': 'BOQ Submitted',
    'HCL-JIGNI - BMS BCS': 'Pending',
    'HCL-JIGNI - BMS BOQ': 'BOQ Submitted',
    'HML - Legacy BCS': 'Pending',
    'HML - Legacy BOQ': 'BOQ Submitted',
    'HSR 1st Floor - Legacy BCS': 'Pending',
    'HSR 1st Floor - Legacy BOQ': 'BOQ Submitted',
    'HSR Salon - Legacy BCS': 'Pending',
    'HSR Salon - Legacy BOQ': 'BOQ Submitted',
    'Happiest Health - Legacy BCS': 'Pending',
    'Happiest Health - Legacy BOQ': 'BOQ Submitted',
    "Havell's Guwahati - Legacy BCS": 'Pending',
    "Havell's Guwahati - Legacy BOQ": 'BOQ Submitted',
    'Horizon Hosur - Legacy BCS': 'Pending',
    'Horizon Hosur - Legacy BOQ': 'BOQ Submitted',
    'Hospital at Thirunelveli - Legacy BCS': 'Pending',
    'Hospital at Thirunelveli - Legacy BOQ': 'BOQ Submitted',
    'Hue Garden - Legacy BCS': 'Pending',
    'Hue Garden - Legacy BOQ': 'BOQ Submitted',
    'Huron - Legacy BCS': 'Pending',
    'Huron - Legacy BOQ': 'BOQ Submitted',
    'ICIPL Upcoming BOQ - ELV BCS': 'Pending',
    'ICIPL Upcoming BOQ - ELV BOQ': 'BOQ Submitted',
    'ICIPL Upcoming BOQ - Electrical BCS': 'Pending',
    'ICIPL Upcoming BOQ - Electrical BOQ': 'BOQ Submitted',
    'ICIPL Upcoming BOQ - HVAC BCS': 'Pending',
    'ICIPL Upcoming BOQ - HVAC BOQ': 'BOQ Submitted',
    'ICIPL Upcoming BOQ - Legacy BCS': 'Pending',
    'ICIPL Upcoming BOQ - Legacy BOQ': 'BOQ Submitted',
    'INCUBEX @ MG1 2F - Legacy BCS': 'Pending',
    'INCUBEX @ MG1 2F - Legacy BOQ': 'BOQ Submitted',
    'Iclean - Legacy BCS': 'Pending',
    'Iclean - Legacy BOQ': 'BOQ Submitted',
    'Incubex_KORMANGALA-5 - HVAC BCS': 'Pending',
    'Incubex_KORMANGALA-5 - HVAC BOQ': 'BOQ Submitted',
    'JLL - Airtel Kochi - Legacy BCS': 'Pending',
    'JLL - Airtel Kochi - Legacy BOQ': 'BOQ Submitted',
    'JPMC - ELV BCS': 'Pending',
    'JPMC - ELV BOQ': 'BOQ Submitted',
    'JPMC - Electrical BCS': 'Pending',
    'JPMC - Electrical BOQ': 'BOQ Submitted',
    'JPMC - HVAC BCS': 'Pending',
    'JPMC - HVAC BOQ': 'BOQ Submitted',
    'JPMC - Legacy BCS': 'Pending',
    'JPMC - Legacy BOQ': 'BOQ Submitted',
    'KRONES GROUP ELE - Legacy BCS': 'Pending',
    'KRONES GROUP ELE - Legacy BOQ': 'BOQ Submitted',
    'Kochi Fire BOQ - Fire System BCS': 'Pending',
    'Kochi Fire BOQ - Fire System BOQ': 'BOQ Submitted',
    'Kudlu Gate - Legacy BCS': 'Pending',
    'Kudlu Gate - Legacy BOQ': 'BOQ Submitted',
    'LTIM - Om Sai - Legacy BCS': 'Pending',
    'LTIM - Om Sai - Legacy BOQ': 'BOQ Submitted',
    'LTIM - Space Theory - Legacy BCS': 'Pending',
    'LTIM - Space Theory - Legacy BOQ': 'BOQ Submitted',
    'Linkedln - Legacy BCS': 'Pending',
    'Linkedln - Legacy BOQ': 'BOQ Submitted',
    'Lounge Bangalore - Electrical BOQ': 'New',
    'Lounge Bangalore - FA BOQ': 'New',
    'Lounge Bangalore - Fire Sprinkler System BOQ': 'In-Progress',
    'Lounge Bangalore - HVAC BOQ': 'In-Progress',
    'M/S Brookfield - Legacy BCS': 'Pending',
    'M/S Brookfield - Legacy BOQ': 'BOQ Submitted',
    'M/S Flipkart - Legacy BCS': 'Pending',
    'M/S Flipkart - Legacy BOQ': 'BOQ Submitted',
    'MBP F3 - Legacy BCS': 'Pending',
    'MBP F3 - Legacy BOQ': 'BOQ Submitted',
    'MBRDI - Legacy BCS': 'Pending',
    'MBRDI - Legacy BOQ': 'BOQ Submitted',
    'MS KPMG - Legacy BCS': 'Pending',
    'MS KPMG - Legacy BOQ': 'BOQ Submitted',
    'MT 3rd floor - Legacy BCS': 'Pending',
    'MT 3rd floor - Legacy BOQ': 'BOQ Submitted',
    'Maconns Noida Project - Legacy BCS': 'Pending',
    'Maconns Noida Project - Legacy BOQ': 'BOQ Submitted',
    'Mantri BLR REFIT - Legacy BCS': 'Pending',
    'Mantri BLR REFIT - Legacy BOQ': 'BOQ Submitted',
    'Material Depot - Kompally - Fire Sprinkler System BOQ': 'In-Progress',
    'Material Depot - Kompally - HVAC VRF-DX BCS': 'Pending',
    'Material Depot - Kompally - HVAC VRF-DX BOQ': 'Revision Submitted',
    'Material Depot Gachibowli - Legacy BCS': 'Pending',
    'Material Depot Gachibowli - Legacy BOQ': 'BOQ Submitted',
    'Max Tower - Legacy BCS': 'Pending',
    'Max Tower - Legacy BOQ': 'BOQ Submitted',
    'Mekin - Raheja Viviera - HVAC BCS': 'Pending',
    'Mekin - Raheja Viviera - HVAC BOQ': 'BOQ Submitted',
    'Met Life - Legacy BCS': 'Pending',
    'Met Life - Legacy BOQ': 'BOQ Submitted',
    'Metalco Global  Extrusions - Legacy BCS': 'Pending',
    'Metalco Global  Extrusions - Legacy BOQ': 'BOQ Submitted',
    'Metro Phase-2: Pune Project - Legacy BCS': 'Pending',
    'Metro Phase-2: Pune Project - Legacy BOQ': 'BOQ Submitted',
    'Mohali 27K - Legacy BCS': 'Pending',
    'Mohali 27K - Legacy BOQ': 'BOQ Submitted',
    'Mott Ahm- 4th floor - Legacy BCS': 'Pending',
    'Mott Ahm- 4th floor - Legacy BOQ': 'BOQ Submitted',
    'Mphasis Phase 2 - Legacy BCS': 'Pending',
    'Mphasis Phase 2 - Legacy BOQ': 'BOQ Submitted',
    'Multigen - Legacy BCS': 'Pending',
    'Multigen - Legacy BOQ': 'BOQ Submitted',
    'Mumbai Airport BOQ - Legacy BCS': 'Pending',
    'Mumbai Airport BOQ - Legacy BOQ': 'BOQ Submitted',
    'NACL Hyderabad - HVAC BCS': 'Pending',
    'NACL Hyderabad - HVAC BOQ': 'BOQ Submitted',
    'NOVOCO - Legacy BCS': 'Pending',
    'NOVOCO - Legacy BOQ': 'BOQ Submitted',
    'New Chennai Project - Legacy BCS': 'Pending',
    'New Chennai Project - Legacy BOQ': 'BOQ Submitted',
    'New Project - Spectarc - Legacy BCS': 'Pending',
    'New Project - Spectarc - Legacy BOQ': 'BOQ Submitted',
    'New Project at Bangalore 13 Dec 25 - Legacy BCS': 'Pending',
    'New Project at Bangalore 13 Dec 25 - Legacy BOQ': 'BOQ Submitted',
    'New Project(Narayana Hospital) - Legacy BCS': 'Pending',
    'New Project(Narayana Hospital) - Legacy BOQ': 'BOQ Submitted',
    'New project Symmetrics - Legacy BCS': 'Pending',
    'New project Symmetrics - Legacy BOQ': 'BOQ Submitted',
    'Nexus Whitefield - Legacy BCS': 'Pending',
    'Nexus Whitefield - Legacy BOQ': 'BOQ Submitted',
    'Noida Airport - Base Kitchen - Legacy BCS': 'Pending',
    'Noida Airport - Base Kitchen - Legacy BOQ': 'BOQ Submitted',
    'Nothing Store - Indira Nagar - Legacy BCS': 'Pending',
    'Nothing Store - Indira Nagar - Legacy BOQ': 'BOQ Submitted',
    'ODC Chennai project - Legacy BCS': 'Pending',
    'ODC Chennai project - Legacy BOQ': 'BOQ Submitted',
    'OSIPL-Philips - IGT EC - Legacy BCS': 'Pending',
    'OSIPL-Philips - IGT EC - Legacy BOQ': 'BOQ Submitted',
    'Origen PMC Chennai - Legacy BCS': 'Pending',
    'Origen PMC Chennai - Legacy BOQ': 'BOQ Submitted',
    'PROJECT-TJ ADMIN - Legacy BCS': 'Pending',
    'PROJECT-TJ ADMIN - Legacy BOQ': 'BOQ Submitted',
    'PWC - Legacy BCS': 'Pending',
    'PWC - Legacy BOQ': 'BOQ Submitted',
    'Padel Pro - ELV BCS': 'Pending',
    'Padel Pro - ELV BOQ': 'BOQ Submitted',
    'Padel Pro - Electrical BCS': 'Pending',
    'Padel Pro - Electrical BOQ': 'BOQ Submitted',
    'Padel Pro - HVAC BCS': 'Pending',
    'Padel Pro - HVAC BOQ': 'BOQ Submitted',
    'Padel Pro - Legacy BCS': 'Pending',
    'Padel Pro - Legacy BOQ': 'BOQ Submitted',
    'Passport Seva Kendra - Legacy BCS': 'Pending',
    'Passport Seva Kendra - Legacy BOQ': 'BOQ Submitted',
    'Pune Project - Legacy BCS': 'Pending',
    'Pune Project - Legacy BOQ': 'BOQ Submitted',
    'Qualcomm - ELV BCS': 'Pending',
    'Qualcomm - ELV BOQ': 'BOQ Submitted',
    'Qualcomm - Electrical BCS': 'Pending',
    'Qualcomm - Electrical BOQ': 'BOQ Submitted',
    'Qualcomm - HVAC BCS': 'Pending',
    'Qualcomm - HVAC BOQ': 'BOQ Submitted',
    'Qualcomm - Legacy BCS': 'Pending',
    'Qualcomm - Legacy BOQ': 'BOQ Submitted',
    'Quest Global - Legacy BCS': 'Pending',
    'Quest Global - Legacy BOQ': 'BOQ Submitted',
    'RFP 23  ELECTRICAL CHENNAI - Legacy BCS': 'Pending',
    'RFP 23  ELECTRICAL CHENNAI - Legacy BOQ': 'BOQ Submitted',
    'RFQ HCL - Legacy BCS': 'Pending',
    'RFQ HCL - Legacy BOQ': 'BOQ Submitted',
    'RFQ Upcoming Bangalore Project - Legacy BCS': 'Pending',
    'RFQ Upcoming Bangalore Project - Legacy BOQ': 'BOQ Submitted',
    'RPK Pune - Legacy BCS': 'Pending',
    'RPK Pune - Legacy BOQ': 'BOQ Submitted',
    'Rebenius - BOQ - Legacy BCS': 'Pending',
    'Rebenius - BOQ - Legacy BOQ': 'BOQ Submitted',
    'Residence of Mr. Ramnarayan - ELV BCS': 'Pending',
    'Residence of Mr. Ramnarayan - ELV BOQ': 'BOQ Submitted',
    'Residence of Mr. Ramnarayan - Electrical BCS': 'Pending',
    'Residence of Mr. Ramnarayan - Electrical BOQ': 'BOQ Submitted',
    'Residence of Mr. Ramnarayan - Legacy BCS': 'Pending',
    'Residence of Mr. Ramnarayan - Legacy BOQ': 'BOQ Submitted',
    'SCHNEIDER BLOCK D2 - Legacy BCS': 'Pending',
    'SCHNEIDER BLOCK D2 - Legacy BOQ': 'BOQ Submitted',
    'SKF - Electrical BCS': 'Pending',
    'SKF - Electrical BOQ': 'BOQ Submitted',
    'SKF - HVAC Ducting BCS': 'Pending',
    'SKF - HVAC Ducting BOQ': 'BOQ Submitted',
    'SKF - Legacy BCS': 'Pending',
    'SKF - Legacy BOQ': 'BOQ Submitted',
    'SKF - custom BCS': 'Pending',
    'SKF - custom BOQ': 'BOQ Submitted',
    'SKY MARK NOIDA - Legacy BCS': 'Pending',
    'SKY MARK NOIDA - Legacy BOQ': 'BOQ Submitted',
    'SPAR HYD - Legacy BCS': 'Pending',
    'SPAR HYD - Legacy BOQ': 'BOQ Submitted',
    'SRI SRI SATTVA MARKETING OFFICE - Legacy BCS': 'Pending',
    'SRI SRI SATTVA MARKETING OFFICE - Legacy BOQ': 'BOQ Submitted',
    'Sample BOQ - Legacy BCS': 'Pending',
    'Sample BOQ - Legacy BOQ': 'BOQ Submitted',
    'Sedana - FIRE FIGHTING BCS': 'Pending',
    'Sedana - FIRE FIGHTING BOQ': 'BOQ Submitted',
    'Shoolagiri - Legacy BCS': 'Pending',
    'Shoolagiri - Legacy BOQ': 'BOQ Submitted',
    'Shop 10 - Legacy BCS': 'Pending',
    'Shop 10 - Legacy BOQ': 'BOQ Submitted',
    'Shop 10 Tech - Legacy BCS': 'Pending',
    'Shop 10 Tech - Legacy BOQ': 'BOQ Submitted',
    'ShowRoom - Legacy BCS': 'Pending',
    'ShowRoom - Legacy BOQ': 'BOQ Submitted',
    'Siemens Chennai - Legacy BCS': 'Pending',
    'Siemens Chennai - Legacy BOQ': 'BOQ Submitted',
    'Siemens Healthineers - Legacy BCS': 'Pending',
    'Siemens Healthineers - Legacy BOQ': 'BOQ Submitted',
    'Siemens Mumbai - Legacy BCS': 'Pending',
    'Siemens Mumbai - Legacy BOQ': 'BOQ Submitted',
    'Siemens Office - Pune - Legacy BCS': 'Pending',
    'Siemens Office - Pune - Legacy BOQ': 'BOQ Submitted',
    'Siemens Project - Legacy BCS': 'Pending',
    'Siemens Project - Legacy BOQ': 'BOQ Submitted',
    'Simpliworks Mindstudio Project - Legacy BCS': 'Pending',
    'Simpliworks Mindstudio Project - Legacy BOQ': 'BOQ Submitted',
    'Sipani City - Electrical BCS': 'Pending',
    'Sipani City - Electrical BOQ': 'BOQ Submitted',
    'Sky Works - Legacy BCS': 'Pending',
    'Sky Works - Legacy BOQ': 'BOQ Submitted',
    'Sky work - Legacy BCS': 'Pending',
    'Sky work - Legacy BOQ': 'BOQ Submitted',
    'Sumadhura - Legacy BCS': 'Pending',
    'Sumadhura - Legacy BOQ': 'BOQ Submitted',
    'Sumadhura Solara Marketing - Legacy BCS': 'Pending',
    'Sumadhura Solara Marketing - Legacy BOQ': 'BOQ Submitted',
    'Suzaki Lab and ODC at Kinfra Ground Floor - Electrical BOQ': 'New',
    'Suzaki Lab and ODC at Kinfra Ground Floor - Fire Sprinkler System BOQ': 'In-Progress',
    'Suzaki Lab and ODC at Kinfra Ground Floor - HVAC BOQ': 'New',
    'Swiggy - Legacy BCS': 'Pending',
    'Swiggy - Legacy BOQ': 'BOQ Submitted',
    'Swiggy New Office - Legacy BCS': 'Pending',
    'Swiggy New Office - Legacy BOQ': 'BOQ Submitted',
    'TAFE PROJECT - Legacy BCS': 'Pending',
    'TAFE PROJECT - Legacy BOQ': 'BOQ Submitted',
    'TEC - ELV BCS': 'Pending',
    'TEC - ELV BOQ': 'BOQ Submitted',
    'TEC - Electrical BCS': 'Pending',
    'TEC - Electrical BOQ': 'BOQ Submitted',
    'TEC - HVAC BCS': 'Pending',
    'TEC - HVAC BOQ': 'BOQ Submitted',
    'TEC - Legacy BCS': 'Pending',
    'TEC - Legacy BOQ': 'BOQ Submitted',
    'TEC WM6 - Legacy BCS': 'Pending',
    'TEC WM6 - Legacy BOQ': 'BOQ Submitted',
    'TEC-PBP-VIMAN NAGAR - Legacy BCS': 'Pending',
    'TEC-PBP-VIMAN NAGAR - Legacy BOQ': 'BOQ Submitted',
    'TEC@summit - Legacy BCS': 'Pending',
    'TEC@summit - Legacy BOQ': 'BOQ Submitted',
    'TEXAS - LAKEVIEW - Rallys - Legacy BCS': 'Pending',
    'TEXAS - LAKEVIEW - Rallys - Legacy BOQ': 'BOQ Submitted',
    'TEXAS - LAKEVIEW - Vaibhav - Legacy BCS': 'Pending',
    'TEXAS - LAKEVIEW - Vaibhav - Legacy BOQ': 'BOQ Submitted',
    'TEXAS - Legacy BCS': 'Pending',
    'TEXAS - Legacy BOQ': 'BOQ Submitted',
    'TEXAS LVA BLOCK 1F 2F - Legacy BCS': 'Pending',
    'TEXAS LVA BLOCK 1F 2F - Legacy BOQ': 'BOQ Submitted',
    'THOUGHT FOCUS KERALA - Legacy BCS': 'Pending',
    'THOUGHT FOCUS KERALA - Legacy BOQ': 'BOQ Submitted',
    'THub Google - ELV BCS': 'Pending',
    'THub Google - ELV BOQ': 'BOQ Submitted',
    'THub Google - Electrical BCS': 'Pending',
    'THub Google - Electrical BOQ': 'BOQ Submitted',
    'THub Google - HVAC BCS': 'Pending',
    'THub Google - HVAC BOQ': 'BOQ Submitted',
    'THub Google - Legacy BCS': 'Pending',
    'THub Google - Legacy BOQ': 'BOQ Submitted',
    'TVS Hosur - Legacy BCS': 'Pending',
    'TVS Hosur - Legacy BOQ': 'BOQ Submitted',
    'TVS_Udaipur - ELV BCS': 'Pending',
    'TVS_Udaipur - ELV BOQ': 'BOQ Submitted',
    'TVS_Udaipur - Electrical BCS': 'Pending',
    'TVS_Udaipur - Electrical BOQ': 'BOQ Submitted',
    'TVS_Udaipur - HVAC BCS': 'Pending',
    'TVS_Udaipur - HVAC BOQ': 'BOQ Submitted',
    'TVS_Udaipur - Legacy BCS': 'Pending',
    'TVS_Udaipur - Legacy BOQ': 'BOQ Submitted',
    'Table Space Food Court - Legacy BCS': 'Pending',
    'Table Space Food Court - Legacy BOQ': 'BOQ Submitted',
    'Technopark - Legacy BCS': 'Pending',
    'Technopark - Legacy BOQ': 'BOQ Submitted',
    'Technosports - Legacy BCS': 'Pending',
    'Technosports - Legacy BOQ': 'BOQ Submitted',
    'Texas Instruments - Lakeview - Legacy BCS': 'Pending',
    'Texas Instruments - Lakeview - Legacy BOQ': 'BOQ Submitted',
    'Titan - Legacy BCS': 'Pending',
    'Titan - Legacy BOQ': 'BOQ Submitted',
    'Toilet refurbishment - Legacy BCS': 'Pending',
    'Toilet refurbishment - Legacy BOQ': 'BOQ Submitted',
    'Training Center - Legacy BCS': 'Pending',
    'Training Center - Legacy BOQ': 'BOQ Submitted',
    'Tulah Clinical Wellness Resort - Legacy BCS': 'Pending',
    'Tulah Clinical Wellness Resort - Legacy BOQ': 'BOQ Submitted',
    'UB City - Legacy BCS': 'Pending',
    'UB City - Legacy BOQ': 'BOQ Submitted',
    'UI Path - Legacy BCS': 'Pending',
    'UI Path - Legacy BOQ': 'BOQ Submitted',
    'UPCOMING 14 BANGALORE - FIRE FIGHTING BCS': 'Pending',
    'UPCOMING 14 BANGALORE - FIRE FIGHTING BOQ': 'BOQ Submitted',
    'UPCOMING ABEE CELESTIAL - Legacy BCS': 'Pending',
    'UPCOMING ABEE CELESTIAL - Legacy BOQ': 'BOQ Submitted',
    'Ujjivan - Fire System BCS': 'Pending',
    'Ujjivan - Fire System BOQ': 'BOQ Submitted',
    'Upcoming CCTV Bangalore Project - Legacy BCS': 'Pending',
    'Upcoming CCTV Bangalore Project - Legacy BOQ': 'BOQ Submitted',
    'Upcoming EV-Gurgaon - Electrical BOQ': 'In-Progress',
    'Upcoming EV-Gurgaon - Fire Sprinkler System BOQ': 'In-Progress',
    'Upcoming EV-Gurgaon - HVAC BOQ': 'In-Progress',
    'Upcoming EV-Gurgaon - Security BOQ': 'In-Progress',
    'Upcoming Hyderbad Auditorium Project - ELV BCS': 'Pending',
    'Upcoming Hyderbad Auditorium Project - ELV BOQ': 'BOQ Submitted',
    'Upcoming Hyderbad Auditorium Project - Electrical BCS': 'Pending',
    'Upcoming Hyderbad Auditorium Project - Electrical BOQ': 'BOQ Submitted',
    'Upcoming Hyderbad Auditorium Project - HVAC BCS': 'Pending',
    'Upcoming Hyderbad Auditorium Project - HVAC BOQ': 'BOQ Submitted',
    'Upcoming Hyderbad Auditorium Project - Legacy BCS': 'Pending',
    'Upcoming Hyderbad Auditorium Project - Legacy BOQ': 'BOQ Submitted',
    'Upcoming JLL - Legacy BCS': 'Pending',
    'Upcoming JLL - Legacy BOQ': 'BOQ Submitted',
    'Upcoming Project - Ahmedabad - Legacy BCS': 'Pending',
    'Upcoming Project - Ahmedabad - Legacy BOQ': 'BOQ Submitted',
    'Upcoming Project -Bangalore - Legacy BCS': 'Pending',
    'Upcoming Project -Bangalore - Legacy BOQ': 'BOQ Submitted',
    'Upcoming Project 11 - Legacy BCS': 'Pending',
    'Upcoming Project 11 - Legacy BOQ': 'BOQ Submitted',
    'Upcoming project-09-GC Package - Legacy BCS': 'Pending',
    'Upcoming project-09-GC Package - Legacy BOQ': 'BOQ Submitted',
    'VIDPL Factory - Electrical BCS': 'Pending',
    'VIDPL Factory - Electrical BOQ': 'BOQ Submitted',
    'VR Mall Food Court - ELV BCS': 'Pending',
    'VR Mall Food Court - ELV BOQ': 'BOQ Submitted',
    'VR Mall Food Court - Electrical BCS': 'Pending',
    'VR Mall Food Court - Electrical BOQ': 'BOQ Submitted',
    'VR Mall Food Court - HVAC BCS': 'Pending',
    'VR Mall Food Court - HVAC BOQ': 'BOQ Submitted',
    'VR Mall Food Court - Legacy BCS': 'Pending',
    'VR Mall Food Court - Legacy BOQ': 'BOQ Submitted',
    'VYAPAR - Legacy BCS': 'Pending',
    'VYAPAR - Legacy BOQ': 'BOQ Submitted',
    'Verizon - Legacy BCS': 'Pending',
    'Verizon - Legacy BOQ': 'BOQ Submitted',
    'WIPRO-GUEST SJP1 - Legacy BCS': 'Pending',
    'WIPRO-GUEST SJP1 - Legacy BOQ': 'BOQ Submitted',
    'Walter P Moore - Legacy BCS': 'Pending',
    'Walter P Moore - Legacy BOQ': 'BOQ Submitted',
    'Wealthy - Legacy BCS': 'Pending',
    'Wealthy - Legacy BOQ': 'BOQ Submitted',
    'Wework - Legacy BCS': 'Pending',
    'Wework - Legacy BOQ': 'BOQ Submitted',
    'Whitefield Project - Legacy BCS': 'Pending',
    'Whitefield Project - Legacy BOQ': 'BOQ Submitted',
    'Wipro_SJP2 - Legacy BCS': 'Pending',
    'Wipro_SJP2 - Legacy BOQ': 'BOQ Submitted',
    'XORIANT@BLR - HVAC BCS': 'Pending',
    'XORIANT@BLR - HVAC BOQ': 'BOQ Submitted',
    'YouTube for brands indiranagar - Legacy BCS': 'Pending',
    'YouTube for brands indiranagar - Legacy BOQ': 'BOQ Submitted',
    'iProfit - Legacy BCS': 'Pending',
    'iProfit - Legacy BOQ': 'BOQ Submitted',
}


def execute():
    if not REVERT_PLAN:
        return

    reverted = 0
    skipped_drifted = 0
    skipped_missing = 0

    for name, target_status in REVERT_PLAN.items():
        # Drift guard: only revert rows still at Done. If the user (or any
        # other process) has already moved this row away from Done since the
        # plan was computed, respect that and skip.
        current_status = frappe.db.get_value(
            "CRM Project Estimation", name, "status"
        )
        if current_status is None:
            skipped_missing += 1
            continue
        if current_status != "Done":
            skipped_drifted += 1
            continue

        frappe.db.set_value(
            "CRM Project Estimation",
            name,
            "status",
            target_status,
            update_modified=False,
        )
        reverted += 1

    frappe.db.commit()

    # Write a small audit CSV alongside the site's private files for traceability.
    # Off-tree (not in version control) since contents are environment-specific.
    try:
        site_path = frappe.get_site_path("private", "files")
        report_path = f"{site_path}/cascade_revert_summary.csv"
        with open(report_path, "w", newline="") as fh:
            writer = csv.writer(fh)
            writer.writerow(["metric", "count"])
            writer.writerow(["plan_size", len(REVERT_PLAN)])
            writer.writerow(["reverted", reverted])
            writer.writerow(["skipped_drifted", skipped_drifted])
            writer.writerow(["skipped_missing", skipped_missing])
    except Exception:
        # Audit CSV is best-effort; never fail the patch over reporting.
        frappe.log_error(
            title="cascade revert summary write failed",
            message=frappe.get_traceback(),
        )

    frappe.logger().info(
        "revert_cascaded_done_estimations: plan=%d reverted=%d "
        "drifted=%d missing=%d",
        len(REVERT_PLAN), reverted, skipped_drifted, skipped_missing,
    )
