name: Build and Push nirmaan_crm
on:
  push:
    tags:
      - '*'

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out frappe_docker
        uses: actions/checkout@v5
        with:
          repository: frappe/frappe_docker

      - name: Build apps.json
        run: |
          mkdir -p "${RUNNER_TEMP}/secrets"
          cat > "${RUNNER_TEMP}/secrets/apps.json" <<EOF
          [
            {
              "url": "https://github.com/Nirmaan-app/nirmaan_crm_frappe_15_postgres_14.git",
              "branch": "${{ github.ref_name }}"
            }
          ]
          EOF

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GAR
        uses: docker/login-action@v4
        with:
          registry: asia-south1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: images/custom/Containerfile
          platforms: linux/amd64
          push: true
          tags: asia-south1-docker.pkg.dev/nirmaan-stack/nirmaan-crm/nirmaan-crm:${{ github.ref_name }}
          build-args: |
            FRAPPE_PATH=https://github.com/frappe/frappe
            FRAPPE_BRANCH=version-15
          secrets: |
            apps_json=${{ runner.temp }}/secrets/apps.json
